import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigService } from '@nestjs/config';
import { SnakeNamingStrategy } from 'typeorm-naming-strategies';
import {
  Project,
  KnowledgeItem,
  WorkflowStep,
  AgentExecution,
  ClarificationQuestion,
  ValidationIssue,
  Document,
  DocumentVersion,
  Settings,
  InterviewSessionEntity,
  DiscoveryCheckpoint,
  RunLog,
  GapAnalysisRun,
  GapAnalysisActiveRun,
  GapAnalysisProposal,
  ProjectContextItem,
  ProjectContextSnapshot,
  ProjectContextCommit,
  PromptTemplate,
  PromptVersion,
  PromptTestRun,
  WorkflowDagDefinition,
  WorkflowDagRun,
  WorkflowDagNodeRun,
  KnowledgeEdge,
  KnowledgeEmbedding,
  ProjectVersion,
  Artifact,
  ArtifactVersion,
  ArtifactDependency,
  AgentSkill,
  AgentSkillExecution,
  WorkflowExecution,
  QualityCheck,
  ModelUsage,
  CanonicalItem,
  CanonicalItemVersion,
  AgentComparison,
  OrchestrationPlanEntity,
  OrchestrationNodeEntity,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        type: 'postgres',
        url: config.get<string>('DATABASE_URL'),
        entities: [
          Project,
          KnowledgeItem,
          WorkflowStep,
          AgentExecution,
          ClarificationQuestion,
          ValidationIssue,
          Document,
          DocumentVersion,
          Settings,
          InterviewSessionEntity,
          DiscoveryCheckpoint,
          RunLog,
          GapAnalysisRun,
          GapAnalysisActiveRun,
          GapAnalysisProposal,
          ProjectContextItem,
          ProjectContextSnapshot,
          ProjectContextCommit,
          PromptTemplate,
          PromptVersion,
          PromptTestRun,
          WorkflowDagDefinition,
          WorkflowDagRun,
          WorkflowDagNodeRun,
          KnowledgeEdge,
          KnowledgeEmbedding,
          ProjectVersion,
          Artifact,
          ArtifactVersion,
          ArtifactDependency,
          AgentSkill,
          AgentSkillExecution,
          WorkflowExecution,
          QualityCheck,
          ModelUsage,
          CanonicalItem,
          CanonicalItemVersion,
          AgentComparison,
          OrchestrationPlanEntity,
          OrchestrationNodeEntity,
        ],
        synchronize: config.get<string>('NODE_ENV') !== 'production',
        namingStrategy: new SnakeNamingStrategy(),
        ssl:
          config.get<string>('NODE_ENV') === 'production'
            ? {
                // Default false preserves prior managed-DB behavior; set
                // DATABASE_SSL_REJECT_UNAUTHORIZED=true to enforce cert checks.
                rejectUnauthorized:
                  config.get<string>('DATABASE_SSL_REJECT_UNAUTHORIZED') === 'true',
              }
            : false,
        logging: false,
      }),
    }),
  ],
  exports: [TypeOrmModule],
})
export class DatabaseModule {}
