/**
 * Artifact Compiler (Phase 9) — pure compile pipeline.
 *
 *   Canonical Project Model → dependency graph → validate completeness →
 *   select sections → compile structured data → provenance + versions →
 *   warnings → markdown document.
 *
 * Deterministic: same inputs → same markdown (stable ordering, no LLM).
 */
import {
  COMPILER_TEMPLATE_VERSION,
  COMPILER_VERSION,
  COMPILER_DOCUMENT_TYPES,
  DOCUMENT_TYPE_MAP,
  REQUIRED_KINDS,
  type CompilationWarning,
  type CompiledDocument,
  type CompileRequest,
  type CompilerArtifact,
  type CompilerDocumentType,
  type CompilerDependencyEdge,
} from './compiler.types';
import { SECTION_PLANS, type RenderedSection } from './compiler.sections';
import { codeBlock, h1, h2, jsonToYaml, kvBlock, paragraph, sortArtifacts } from './compiler.markdown';

export function isCompilerDocumentType(value: string): value is CompilerDocumentType {
  return (COMPILER_DOCUMENT_TYPES as readonly string[]).includes(value);
}

/**
 * Compile canonical artifacts into a project document.
 * Never invokes an LLM — canonical facts come only from the project model.
 */
export function compileDocument(request: CompileRequest): CompiledDocument {
  const { documentType, artifacts, dependencies = [] } = request;
  const compilerVersion = request.compilerVersion ?? COMPILER_VERSION;
  const templateVersion = request.templateVersion ?? COMPILER_TEMPLATE_VERSION;
  const generatedAt = request.generatedAt ?? new Date().toISOString();

  const warnings: CompilationWarning[] = [];
  const missingRequiredKinds: string[] = [];

  // 1. Completeness validation.
  const kindsPresent = new Set(artifacts.map((a) => a.kind));
  for (const kind of REQUIRED_KINDS[documentType]) {
    if (!kindsPresent.has(kind)) {
      missingRequiredKinds.push(kind);
      warnings.push({
        type: 'missing-required-kind',
        message: `no artifacts of kind '${kind}' — section will be empty`,
      });
    }
  }

  // 2. Provenance + confidence + dependency warnings.
  for (const artifact of artifacts) {
    if (!artifact.provenance?.epistemicClass) {
      warnings.push({ type: 'missing-provenance', message: `artifact '${artifact.externalId}' has no provenance`, artifactKey: artifact.externalId });
    }
    if (artifact.confidence != null && artifact.confidence < 50) {
      warnings.push({ type: 'low-confidence', message: `artifact '${artifact.externalId}' has low confidence (${artifact.confidence})`, artifactKey: artifact.externalId });
    }
  }
  const knownIds = new Set(artifacts.map((a) => a.externalId));
  for (const edge of dependencies) {
    if (!knownIds.has(edge.sourceArtifactId) || !knownIds.has(edge.targetArtifactId)) {
      warnings.push({ type: 'dangling-dependency', message: `dependency ${edge.sourceArtifactId} -> ${edge.targetArtifactId} references unknown artifacts` });
    }
  }

  // 3. Compile sections deterministically.
  const sections: RenderedSection[] = SECTION_PLANS[documentType]
    .map((render) => render(artifacts))
    .filter((section) => section.body.length > 0);
  for (const section of SECTION_PLANS[documentType].map((render) => render(artifacts))) {
    if (section.body.length === 0) {
      warnings.push({ type: 'empty-section', message: `section '${section.title}' is empty` });
    }
  }

  const title = documentTitle(documentType);
  const parts: string[] = [h1(title), paragraph(`Generated by Artifact Compiler v${compilerVersion} (template v${templateVersion}) at ${generatedAt}.`)];

  // 4. Metadata block (source versions, compiler version, generated by).
  if (request.options?.includeMetadata !== false) {
    parts.push(
      h2('Document Metadata'),
      kvBlock([
        ['Document Type', documentType],
        ['Compiler Version', compilerVersion],
        ['Template Version', templateVersion],
        ['Generated At', generatedAt],
        ['Source Artifacts', artifacts.length],
        ['Source Artifact Versions', sourceVersions(artifacts)],
      ]),
    );
  }

  // 5. Sections.
  for (const section of sections) {
    parts.push(h2(section.title), section.body);
  }

  // 6. Traceability section (dependency graph).
  if (request.options?.includeTraceability !== false && dependencies.length > 0) {
    const rows = sortArtifacts(dependencies.map((d) => ({ kind: 'dependency', externalId: d.sourceArtifactId }))).map((d) => {
      const edge = dependencies.find((e) => e.sourceArtifactId === d.externalId)!;
      return [edge.sourceArtifactId, edge.relation, edge.targetArtifactId];
    });
    parts.push(h2('Traceability'), ['| Source | Relation | Target |', '| --- | --- | --- |', ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n'));
  }

  // 7. Provenance section (source references preserved).
  if (request.options?.includeProvenance !== false) {
    const provenanceRows = sortArtifacts(artifacts)
      .map((a) => {
        const cls = a.provenance?.epistemicClass ?? 'UNKNOWN';
        const sources = (a.provenance?.sources ?? []).map((s) => `${s.category}${s.refId ? `:${s.refId}` : ''}`).join(', ') || '-';
        return [a.externalId, a.kind, cls, sources];
      });
    if (provenanceRows.length > 0) {
      parts.push(h2('Provenance'), ['| Artifact | Kind | Epistemic Class | Sources |', '| --- | --- | --- | --- |', ...provenanceRows.map((r) => `| ${r.join(' | ')} |`)].join('\n'));
    }
  }

  // 8. BUILD_PROMPT: append the canonical model dump for AI builders.
  if (documentType === 'BUILD_PROMPT') {
    parts.push(h2('Canonical Model'), codeBlock('yaml', jsonToYaml(sortArtifacts(artifacts).map((a) => ({
      id: a.externalId,
      kind: a.kind,
      title: a.title,
      summary: a.summary ?? '',
      body: a.body ?? {},
      confidence: a.confidence ?? null,
      epistemicClass: a.provenance?.epistemicClass ?? null,
    })))));
  }

  return {
    documentType,
    persistedDocumentType: DOCUMENT_TYPE_MAP[documentType],
    markdown: parts.join('\n\n') + '\n',
    warnings,
    missingRequiredKinds,
    sourceArtifactCount: artifacts.length,
    compilerVersion,
    templateVersion,
    generatedAt,
  };
}

export function documentTitle(documentType: CompilerDocumentType): string {
  const titles: Record<CompilerDocumentType, string> = {
    FRD: 'Functional Requirements Document',
    USER_STORIES: 'User Stories & Acceptance Criteria',
    TECHNICAL_ARCHITECTURE: 'Technical Architecture (HLD)',
    DATABASE_DESIGN: 'Database Design',
    API_SPECIFICATION: 'API Specification (OpenAPI)',
    QA_DOCUMENT: 'QA Plan & Test Cases',
    SOW: 'Scope of Work',
    BUILD_PROMPT: 'Build Prompt',
  };
  return titles[documentType];
}

function sourceVersions(artifacts: CompilerArtifact[]): string {
  const versions = artifacts
    .filter((a) => a.version != null)
    .map((a) => `${a.externalId}@v${a.version}`);
  return versions.length > 0 ? versions.join(', ') : 'n/a';
}

/** Re-exported for convenience. */
export type { CompilerArtifact, CompilerDependencyEdge };
