import { Injectable, Logger } from '@nestjs/common';
import { CanonicalModelService } from '../canonical/canonical-model.service';
import { QualityEngineService } from '../validation/quality-engine.service';
import { DocumentGeneratorService } from '../documents/document-generator.service';
import { mapKnowledgeBatchToCanonical, type CanonicalCandidate } from './legacy-canonical.mapper';
import { COMPILER_DOCUMENT_TYPES } from '../documents/compiler.types';
import type { CanonicalKind } from '../canonical/canonical.types';
import type { KnowledgeItemSummary, NewKnowledgeItem } from '../../agents/types';

export interface PipelineFoundationOptions {
  /** Enable canonical dual-write from legacy agent output (default true). */
  canonicalWrite?: boolean;
  /** Enable per-artifact quality evaluation (default true). */
  qualityEvaluation?: boolean;
  /** Enable auto-compile of documents at pipeline completion (default false). */
  autoCompile?: boolean;
  /** Full project quality run at pipeline completion (default true). */
  autoQuality?: boolean;
}

/**
 * PipelineFoundationService — the bridge that makes the foundation
 * architecture run automatically inside the existing pipeline.
 *
 *   legacy agent output
 *     → canonical dual-write (validated; invalid output is never trusted)
 *     → per-artifact quality evaluation
 *     → (at completion) compiled documents from the canonical model
 *
 * Everything is best-effort: a foundation failure never breaks the legacy
 * pipeline stage.
 */
@Injectable()
export class PipelineFoundationService {
  private readonly logger = new Logger(PipelineFoundationService.name);

  constructor(
    private readonly canonical: CanonicalModelService,
    private readonly quality: QualityEngineService,
    private readonly compiler: DocumentGeneratorService,
  ) {}

  private options(): PipelineFoundationOptions {
    const env = process.env;
    return {
      canonicalWrite: env.FOUNDATION_CANONICAL_WRITE !== 'false',
      qualityEvaluation: env.FOUNDATION_QUALITY_PER_STAGE !== 'false',
      autoCompile: env.FOUNDATION_COMPILER_AUTO === 'true',
      autoQuality: env.FOUNDATION_AUTO_QUALITY !== 'false',
    };
  }

  /**
   * Dual-write legacy agent knowledge items into the canonical model.
   * Mapped candidates are validated by the canonical pipeline (dry-run);
   * only schema-valid items are persisted.
   */
  async persistCanonicalFromAgent(
    projectId: string,
    agentKey: string,
    knowledgeItems: NewKnowledgeItem[],
  ): Promise<{ persisted: number; skipped: number }> {
    const opts = this.options();
    if (!opts.canonicalWrite) return { persisted: 0, skipped: 0 };

    let persisted = 0;
    let skipped = 0;
    for (const candidate of mapKnowledgeBatchToCanonical(knowledgeItems)) {
      try {
        // Validate before trusting: dry-run first.
        await this.canonical.ingest(projectId, toIngestInput(candidate, agentKey), { dryRun: true });
        await this.canonical.ingest(projectId, toIngestInput(candidate, agentKey), {
          metadata: { producerAgent: agentKey, source: 'pipeline-dual-write' },
        });
        persisted += 1;
      } catch {
        skipped += 1;
      }
    }
    if (persisted > 0 || skipped > 0) {
      this.logger.log(
        `Canonical dual-write for ${agentKey} (${projectId}): persisted ${persisted}, skipped ${skipped}`,
      );
    }
    return { persisted, skipped };
  }

  /** Evaluate the canonical artifacts written by the just-finished stage. */
  async evaluateCanonicalArtifacts(projectId: string): Promise<void> {
    const opts = this.options();
    if (!opts.qualityEvaluation) return;
    try {
      await this.quality.evaluateProject(projectId);
    } catch (err) {
      this.logger.warn(`Per-stage quality evaluation failed (${projectId}): ${err instanceof Error ? err.message : err}`);
    }
  }

  /** Auto-generate compiled documents from canonical data at completion. */
  async generateCompiledDocuments(projectId: string): Promise<string[]> {
    const opts = this.options();
    if (!opts.autoCompile) return [];
    const generated: string[] = [];
    for (const docType of COMPILER_DOCUMENT_TYPES) {
      try {
        const doc = await this.compiler.generate(projectId, docType, {
          source: 'both',
          changeSummary: 'Auto-generated by Artifact Compiler on pipeline completion',
          triggerEvent: 'pipeline-completion',
        });
        if (doc.sourceArtifactCount > 0) generated.push(docType);
      } catch (err) {
        this.logger.warn(`Auto-compile ${docType} skipped (${projectId}): ${err instanceof Error ? err.message : err}`);
      }
    }
    return generated;
  }

  /** Full-project quality evaluation at pipeline completion (env-gated). */
  async evaluateProjectAtCompletion(projectId: string): Promise<void> {
    const opts = this.options();
    if (!opts.autoQuality) return;
    try {
      await this.quality.evaluateProject(projectId);
    } catch (err) {
      this.logger.warn(
        `Completion quality evaluation failed (${projectId}): ${err instanceof Error ? err.message : err}`,
      );
    }
  }

  /** Enrich an agent context with canonical items (context engine integration). */
  async enrichKnowledgeWithCanonical(
    projectId: string,
    knowledgeItems: KnowledgeItemSummary[],
  ): Promise<KnowledgeItemSummary[]> {
    try {
      const canonicalItems = await this.canonical.listAll(projectId);
      if (canonicalItems.length === 0) return knowledgeItems;
      const existing = new Set(knowledgeItems.map((k) => k.externalId).filter((x): x is string => !!x));
      const extras: KnowledgeItemSummary[] = canonicalItems
        .filter((c) => !existing.has(c.externalId))
        .map((c) => ({
          externalId: c.externalId,
          type: c.kind,
          title: c.title,
          description: c.summary ?? null,
          status: c.status,
          source: (c.provenance as { producedBy?: string })?.producedBy ?? null,
        }));
      return [...knowledgeItems, ...extras];
    } catch (err) {
      this.logger.warn(`Canonical context enrichment failed (${projectId}): ${err instanceof Error ? err.message : err}`);
      return knowledgeItems;
    }
  }
}

function toIngestInput(candidate: CanonicalCandidate, agentKey: string): Record<string, unknown> {
  return {
    externalId: candidate.externalId,
    kind: candidate.kind as CanonicalKind,
    title: candidate.title,
    summary: candidate.summary,
    status: 'CONFIRMED',
    provenance: {
      epistemicClass: candidate.epistemicClass,
      sources: candidate.sources,
      producedBy: agentKey,
      schemaVersion: '1.0',
    },
    body: candidate.body,
  };
}
