import { Injectable } from '@nestjs/common';
import { LlmService } from '../llm/llm.service';
import type { AgentContext, AgentResult, KnowledgeItemSummary } from './types';

@Injectable()
export class CompilerService {
  constructor(private readonly llm: LlmService) {}

  async run(ctx: AgentContext): Promise<AgentResult> {
    // Build the detailed package from full RKB data (no truncation of stored facts).
    // LLM is only used for a short executive narrative on top.
    const body = this.compileFromKnowledge(ctx);
    let executiveSummary = '';

    try {
      const r = await this.llm.generateText([
        {
          role: 'system',
          content:
            'Write a detailed Executive Summary (250-400 words) for a software engineering documentation package. Cover problem, solution, users, MVP scope, key risks, and recommended next steps. Use professional prose. Do not invent features not implied by the idea.',
        },
        {
          role: 'user',
          content: `Project: ${ctx.projectName}\n\nIdea:\n${ctx.idea}\n\nKey signals:\n${this.briefSignals(ctx.knowledgeItems)}`,
        },
      ]);
      executiveSummary = r.content.trim();
    } catch {
      executiveSummary = this.fallbackExecutiveSummary(ctx);
    }

    const documentContent = [
      `# ${ctx.projectName}`,
      '',
      `> Generated by Crystallize — Compiler Agent`,
      '',
      `## 1. Executive Summary`,
      '',
      executiveSummary,
      '',
      body,
    ].join('\n');

    return {
      success: true,
      agentKey: 'compiler',
      knowledgeItems: [
        {
          type: 'COMPILED_DOCUMENT',
          title: `${ctx.projectName} — Compiled Requirement Document`,
          description: `Executive Summary:

${executiveSummary}

Full document contains specifications, requirements, and technical details.`,
          status: 'CONFIRMED' as const,
          sourceCategory: 'ai_analysis' as const,
          confidence: 85,
        },
      ],
      questions: [],
      documentContent,
      warnings: [],
    };
  }

  /**
   * Generate the standalone Developer-Ready Build Prompt document.
   * Called by the BUILD_PROMPT_GENERATION pipeline stage.
   */
  async buildPrompt(ctx: AgentContext): Promise<AgentResult> {
    return {
      success: true,
      agentKey: 'build-prompt-generation',
      knowledgeItems: [],
      questions: [],
      documentContent: this.developerBuildPrompt(ctx),
      warnings: [],
    };
  }

  private briefSignals(items: KnowledgeItemSummary[]): string {
    const pick = (types: string[], n = 5) =>
      items
        .filter((i) => types.includes(i.type))
        .slice(0, n)
        .map((i) => `- [${i.type}] ${i.title}`)
        .join('\n');

    return [
      pick(['DISCOVERY_SUMMARY', 'BA_SUMMARY', 'PRODUCT_VISION', 'MVP_SCOPE']),
      pick(['FEATURE', 'MODULE', 'FUNCTIONAL_REQUIREMENT'], 8),
      pick(['SECURITY_REPORT', 'ESTIMATION_REPORT', 'VALIDATION_SCORES'], 3),
    ]
      .filter(Boolean)
      .join('\n');
  }

  private fallbackExecutiveSummary(ctx: AgentContext): string {
    const discovery = itemsOf(ctx.knowledgeItems, 'DISCOVERY_SUMMARY')[0];
    return [
      `${ctx.projectName} addresses the following opportunity:`,
      '',
      ctx.idea,
      '',
      discovery?.description ??
        'The multi-agent pipeline produced discovery, requirements, architecture, security, QA, and estimation artifacts documented in the sections below.',
    ].join('\n');
  }

  private compileFromKnowledge(ctx: AgentContext): string {
    const items = ctx.knowledgeItems;
    const sections: string[] = [];

    sections.push(
      this.section('2. Discovery Report', [
        this.block('Problem & Solution', items, ['DISCOVERY_SUMMARY']),
        this.list('Confirmed Facts', items, ['CONFIRMED_FACT']),
        this.list('Business Goals', items, ['BUSINESS_GOAL']),
        this.list('User Goals', items, ['USER_GOAL']),
        this.list('User Types', items, ['USER_TYPE']),
        this.list('Early Risks', items, ['RISK']),
        this.list('Assumptions', items, ['ASSUMPTION']),
      ]),
    );

    sections.push(
      this.section('3. Research Report', [
        this.block('Research Summary', items, ['RESEARCH_SUMMARY']),
        this.list('Competitors', items, ['COMPETITOR']),
        this.list('Technology Suggestions', items, ['TECHNOLOGY_SUGGESTION']),
        this.list('API / Integration Landscape', items, ['API_RESEARCH']),
        this.list('Compliance Notes', items, ['COMPLIANCE_NOTE']),
        this.list('Industry Standards', items, ['INDUSTRY_STANDARD']),
        this.list('Research Risks', items, ['RESEARCH_RISK']),
      ]),
    );

    sections.push(
      this.section('4. Business Requirements (BRD)', [
        this.block('Business Analysis Summary', items, ['BA_SUMMARY']),
        this.list('Business Objectives', items, ['BUSINESS_OBJECTIVE']),
        this.list('Stakeholders', items, ['STAKEHOLDER']),
        this.detailedList('Business Requirements', items, ['BUSINESS_REQUIREMENT']),
        this.detailedList('Business Rules', items, ['BUSINESS_RULE']),
        this.list('Constraints', items, ['CONSTRAINT']),
        this.list('Business Risks', items, ['BUSINESS_RISK']),
        this.block('Scope', items, ['SCOPE']),
      ]),
    );

    sections.push(
      this.section('5. Product Requirements (PRD)', [
        this.block('Product Vision', items, ['PRODUCT_VISION']),
        this.block('Value Proposition', items, ['VALUE_PROPOSITION']),
        this.list('Personas', items, ['PERSONA']),
        this.list('Modules', items, ['MODULE']),
        this.detailedList('Features (Prioritized)', items, ['FEATURE']),
        this.block('MVP Scope', items, ['MVP_SCOPE']),
        this.list('Success Metrics', items, ['SUCCESS_METRIC']),
      ]),
    );

    sections.push(
      this.section('6. Software Requirements Specification (SRS)', [
        this.intro(
          'Functional requirements below include actors, modules, priorities, acceptance criteria, validation rules, and error conditions where captured by the Requirements Agent.',
        ),
        this.detailedList('Functional Requirements', items, ['FUNCTIONAL_REQUIREMENT']),
        this.list('Non-Functional / Constraints', items, ['CONSTRAINT']),
        this.list('Dependencies & Integrations', items, [
          'API_RESEARCH',
          'API_SPEC',
          'TECHNOLOGY_SUGGESTION',
        ]),
      ]),
    );

    sections.push(
      this.section('7. User Stories & Use Cases', [
        this.detailedList('User Stories', items, ['USER_STORY']),
        this.scenarioGuidance(),
      ]),
    );

    sections.push(
      this.section('8. UX Specification', [
        this.block('UX Summary & Navigation', items, ['UX_SUMMARY']),
        this.list('UX Personas', items, ['UX_PERSONA', 'PERSONA']),
        this.detailedList('User Journeys', items, ['USER_JOURNEY']),
        this.detailedList('Screen Inventory', items, ['SCREEN']),
        this.list('UX Guidelines', items, ['UX_GUIDELINE']),
        this.list('Accessibility Requirements', items, ['ACCESSIBILITY_REQUIREMENT']),
        this.detailedList('Wireframe Descriptions', items, ['WIREFRAME']),
      ]),
    );

    sections.push(
      this.section('9. Database Design', [
        this.block('Design Summary / ER Overview', items, ['DATABASE_DESIGN']),
        this.detailedList('Tables', items, ['DB_TABLE']),
        this.detailedList('Relationships', items, ['DB_RELATIONSHIP']),
        this.list('Constraints', items, ['DB_CONSTRAINT']),
        this.list('Indexes', items, ['DB_INDEX']),
        this.detailedList('Data Dictionary', items, ['DATA_DICTIONARY']),
      ]),
    );

    sections.push(
      this.section('10. AI Architecture', [
        this.block('AI Architecture Summary', items, ['AI_ARCHITECTURE']),
        this.list('LLM Selection', items, ['LLM_SELECTION']),
        this.detailedList('Prompt Strategy', items, ['PROMPT_STRATEGY']),
        this.list('Embeddings', items, ['EMBEDDING_DESIGN']),
        this.list('Vector Store', items, ['VECTOR_STORE']),
        this.list('Memory / Context', items, ['AI_MEMORY']),
        this.detailedList('Guardrails', items, ['AI_GUARDRAIL']),
      ]),
    );

    sections.push(
      this.section('11. Solution Architecture & API Specification', [
        this.block('Architecture Summary', items, ['SOLUTION_ARCHITECTURE']),
        this.detailedList('System Components', items, ['SYSTEM_COMPONENT']),
        this.detailedList('API Specifications', items, ['API_SPEC']),
        this.list('Events / Queues', items, ['EVENT_FLOW']),
        this.list('Infrastructure', items, ['INFRASTRUCTURE']),
        this.list('Deployment', items, ['DEPLOYMENT']),
        this.list('Logging & Monitoring', items, ['OBSERVABILITY']),
      ]),
    );

    sections.push(
      this.section('12. Security Report & Threat Model', [
        this.block('Security Summary', items, ['SECURITY_REPORT']),
        this.detailedList('Authentication & Authorization', items, ['SECURITY_AUTH']),
        this.detailedList('OWASP Findings', items, ['OWASP_FINDING']),
        this.list('Encryption & Secrets', items, ['SECURITY_ENCRYPTION']),
        this.list('API Security', items, ['API_SECURITY']),
        this.list('Compliance', items, ['SECURITY_COMPLIANCE', 'COMPLIANCE_NOTE']),
        this.detailedList('Threat Model', items, ['THREAT_MODEL']),
      ]),
    );

    sections.push(
      this.section('13. QA Strategy & Test Cases', [
        this.block('QA Plan & Strategy', items, ['QA_PLAN']),
        this.list('Test Plan Items', items, ['TEST_PLAN_ITEM']),
        this.detailedList('Functional Test Cases', items, ['TEST_CASE']),
        this.detailedList('Regression Tests', items, ['REGRESSION_TEST']),
        this.detailedList('Performance Tests', items, ['PERFORMANCE_TEST']),
        this.detailedList('Security Tests', items, ['SECURITY_TEST']),
        this.testScenarioGuidance(),
      ]),
    );

    sections.push(
      this.section('14. Estimation & Sprint Plan', [
        this.block('Estimation Summary', items, ['ESTIMATION_REPORT']),
        this.list('Team Composition', items, ['TEAM_ROLE']),
        this.detailedList('Timeline', items, ['TIMELINE']),
        this.list('Cost Estimate', items, ['COST_ESTIMATE']),
        this.detailedList('Sprint Plan', items, ['SPRINT_PLAN']),
        this.list('Estimation Risks', items, ['ESTIMATION_RISK']),
      ]),
    );

    sections.push(
      this.section('15. Risks & Gap Analysis', [
        this.list('Product / Discovery Risks', items, ['RISK', 'BUSINESS_RISK', 'RESEARCH_RISK']),
        this.list('Security Risks', items, ['OWASP_FINDING', 'THREAT_MODEL']),
        this.list('Estimation Risks', items, ['ESTIMATION_RISK']),
        this.block('Validation Findings', items, ['VALIDATION_SCORES']),
        this.gapGuidance(),
      ]),
    );

    sections.push(
      this.section('16. Validation Summary', [
        this.block('Critic / Validation Scores', items, ['VALIDATION_SCORES']),
        this.outro(),
      ]),
    );

    sections.push(
      this.section('17. Visual Architecture & Flow Diagrams', [
        this.architectureDiagram(items),
        this.workflowDiagram(items),
        this.dataFlowDiagram(items),
      ]),
    );

    sections.push(this.section('18. Appendix — Full Knowledge Inventory', [this.inventory(items)]));

    sections.push(
      this.section('19. Developer-Ready Build Prompt', [this.developerBuildPrompt(ctx)]),
    );

    return sections.filter(Boolean).join('\n\n');
  }

  private section(title: string, parts: Array<string | null>): string {
    const body = parts.filter((p): p is string => !!p && p.trim().length > 0).join('\n\n');
    if (!body.trim()) {
      return `## ${title}\n\n_No artifacts were generated for this section._`;
    }
    return `## ${title}\n\n${body}`;
  }

  private intro(text: string): string {
    return text;
  }

  private block(label: string, items: KnowledgeItemSummary[], types: string[]): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i) => {
        const header = i.externalId ? `**${i.externalId} — ${i.title}**` : `**${i.title}**`;
        return `${header}\n\n${i.description?.trim() || '_No description provided._'}`;
      }),
    ].join('\n');
  }

  private list(label: string, items: KnowledgeItemSummary[], types: string[]): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i) => {
        const id = i.externalId ? `\`${i.externalId}\` ` : '';
        const desc = i.description?.trim();
        return desc ? `- **${id}${i.title}**: ${singleLine(desc)}` : `- **${id}${i.title}**`;
      }),
    ].join('\n');
  }

  private detailedList(
    label: string,
    items: KnowledgeItemSummary[],
    types: string[],
  ): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i, idx) => {
        const id = i.externalId ? `${i.externalId} — ` : '';
        return [
          `#### ${idx + 1}. ${id}${i.title}`,
          '',
          i.description?.trim() || '_No detailed description captured._',
          '',
          i.status ? `_Status: ${i.status}_` : '',
        ]
          .filter(Boolean)
          .join('\n');
      }),
    ].join('\n');
  }

  private scenarioGuidance(): string {
    return [
      '### Scenario Coverage Checklist',
      '',
      'For each user story / FR above, implementation and QA should explicitly cover:',
      '',
      '1. **Happy path** — primary successful flow with valid inputs',
      '2. **Validation failures** — missing/invalid fields, malformed files, bad formats',
      '3. **Authorization failures** — unauthenticated / unauthorized access',
      '4. **Empty / edge states** — no data, first-time user, large payloads',
      '5. **Concurrency / retries** — duplicate submissions, network retries, idempotency',
      '6. **External dependency failures** — OCR/LLM/API timeouts and degraded mode',
      '7. **Auditability** — who did what, when, with which artifact',
    ].join('\n');
  }

  private testScenarioGuidance(): string {
    return [
      '### Recommended End-to-End Scenarios',
      '',
      '- New user registration → login → upload brochure → view extraction → receive recommendations',
      '- Invalid brochure upload (wrong type/corrupt/oversized) → clear error + retry',
      '- Partial extraction confidence → human review / confirmation step',
      '- Area research with missing geo data → graceful fallback messaging',
      '- Admin views audit logs and security events',
      '- Performance: concurrent uploads and recommendation generation under load',
      '- Security: auth bypass attempts, IDOR on brochure/project IDs, injection on metadata fields',
    ].join('\n');
  }

  private gapGuidance(): string {
    return [
      '### How to Use Gap Analysis',
      '',
      '- Treat Critic CRITICAL/HIGH issues as release blockers until resolved or explicitly accepted',
      '- Trace each FR to at least one test case and one UI screen',
      '- Confirm every MVP feature has data model + API + UX coverage',
      '- Re-run Validation after major requirement changes',
    ].join('\n');
  }

  private outro(): string {
    return [
      '### Sign-off Notes',
      '',
      'This package consolidates outputs from Discovery, Research, Business Analysis, Product Management, Requirements, UX, Data/AI/Solution Architecture, Security, QA, Estimation, and Critic agents.',
      '',
      'Recommended next step: resolve open validation issues, confirm MVP scope with stakeholders, then begin Sprint 1 implementation against the prioritized FRs and sprint plan.',
    ].join('\n');
  }

  private architectureDiagram(items: KnowledgeItemSummary[]): string | null {
    const features = itemsOf(items, 'FEATURE', 'MODULE');
    const techs = itemsOf(items, 'TECHNOLOGY_SUGGESTION');
    const apiSpecs = itemsOf(items, 'API_SPECIFICATION');

    if (features.length === 0 && techs.length === 0 && apiSpecs.length === 0) return null;

    const nodes: string[] = [];
    const edges: string[] = [];

    features.forEach((f, i) => {
      const nodeId = `feat_${i}`;
      nodes.push(`    ${nodeId}["${f.title}"]`);
    });

    techs.forEach((t, i) => {
      const nodeId = `tech_${i}`;
      nodes.push(`    ${nodeId}["${t.title}"]`);
      if (features[i]) edges.push(`    feat_${i} --> ${nodeId}`);
    });

    apiSpecs.forEach((a, i) => {
      const nodeId = `api_${i}`;
      nodes.push(`    ${nodeId}["${a.title}"]`);
      if (features[i]) edges.push(`    feat_${i} --> ${nodeId}`);
    });

    return [
      '### System Architecture Overview',
      '',
      '```mermaid',
      'graph LR',
      ...nodes,
      ...edges,
      '```',
    ].join('\n');
  }

  private workflowDiagram(items: KnowledgeItemSummary[]): string | null {
    const requirements = itemsOf(items, 'FUNCTIONAL_REQUIREMENT');
    if (requirements.length === 0) return null;

    const steps = requirements.slice(0, 8).map((r, i) => {
      const label = r.externalId ? `${r.externalId}: ${r.title}` : r.title;
      return `    Step${i + 1}["${label}"]`;
    });

    const edges = Array.from(
      { length: steps.length - 1 },
      (_, i) => `    Step${i + 1} --> Step${i + 2}`,
    );

    return [
      '### User Journey & Workflow Flow',
      '',
      '```mermaid',
      'graph LR',
      ...steps,
      ...edges,
      '```',
    ].join('\n');
  }

  private dataFlowDiagram(items: KnowledgeItemSummary[]): string | null {
    const entities = itemsOf(items, 'DATA_ENTITY', 'DOMAIN_ENTITY');
    const apis = itemsOf(items, 'API_ENDPOINT');

    if (entities.length === 0 && apis.length === 0) return null;

    const nodes: string[] = [];
    const edges: string[] = [];

    entities.forEach((e, i) => {
      nodes.push(`    ${e.type}_${i}["${e.title}"]`);
    });

    apis.forEach((a, i) => {
      const apiNodeId = `api_${i}`;
      nodes.push(`    ${apiNodeId}["${a.title}"]`);
      const targetEntity = entities[i % entities.length];
      if (targetEntity) {
        edges.push(`    ${apiNodeId} --> ${targetEntity.type}_${entities.indexOf(targetEntity)}`);
      }
    });

    return [
      '### Data Flow & Entity Relationships',
      '',
      '```mermaid',
      'graph LR',
      ...nodes,
      ...edges,
      '```',
    ].join('\n');
  }

  private inventory(items: KnowledgeItemSummary[]): string {
    const counts = new Map<string, number>();
    for (const i of items) {
      counts.set(i.type, (counts.get(i.type) ?? 0) + 1);
    }
    const rows = [...counts.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([type, count]) => `| ${type} | ${count} |`)
      .join('\n');

    return [
      `Total knowledge items: **${items.length}**`,
      '',
      '| Type | Count |',
      '|---|---:|',
      rows,
    ].join('\n');
  }

  /** Produce a self-contained, copy-pasteable build prompt that turns the whole
   *  compiled package into an implementation brief any AI coding agent can
   *  execute end-to-end ("development ready anywhere"). Inlines the key
   *  artifacts (requirements, stack, data model, APIs, screens, security, QA)
   *  and gives explicit scaffolding + definition-of-done instructions. */
  private developerBuildPrompt(ctx: AgentContext): string {
    const items = ctx.knowledgeItems;

    const frs = itemsOf(items, 'FUNCTIONAL_REQUIREMENT');
    const techs = itemsOf(items, 'TECHNOLOGY_SUGGESTION');
    const llms = itemsOf(items, 'LLM_SELECTION');
    const ai = itemsOf(items, 'AI_ARCHITECTURE', 'PROMPT_STRATEGY', 'EMBEDDING_DESIGN', 'VECTOR_STORE');
    const tables = itemsOf(items, 'DB_TABLE', 'DATA_ENTITY', 'DOMAIN_ENTITY');
    const rels = itemsOf(items, 'DB_RELATIONSHIP');
    const dbConstraints = itemsOf(items, 'DB_CONSTRAINT');
    const indexes = itemsOf(items, 'DB_INDEX');
    const dictionary = itemsOf(items, 'DATA_DICTIONARY');
    const apis = itemsOf(items, 'API_SPEC', 'API_ENDPOINT');
    const screens = itemsOf(items, 'SCREEN');
    const journeys = itemsOf(items, 'USER_JOURNEY');
    const ux = itemsOf(items, 'UX_GUIDELINE', 'ACCESSIBILITY_REQUIREMENT');
    const personas = itemsOf(items, 'PERSONA', 'USER_TYPE', 'STAKEHOLDER');
    const nfr = itemsOf(items, 'CONSTRAINT');
    const security = itemsOf(
      items,
      'SECURITY_AUTH',
      'SECURITY_ENCRYPTION',
      'API_SECURITY',
      'SECURITY_COMPLIANCE',
      'OWASP_FINDING',
      'THREAT_MODEL',
    );
    const qa = itemsOf(
      items,
      'QA_PLAN',
      'TEST_CASE',
      'TEST_PLAN_ITEM',
      'REGRESSION_TEST',
      'PERFORMANCE_TEST',
      'SECURITY_TEST',
    );
    const validation = itemsOf(items, 'VALIDATION_SCORES');
    const scope = itemsOf(items, 'MVP_SCOPE', 'SCOPE', 'SUCCESS_METRIC');
    const eventFlow = itemsOf(items, 'EVENT_FLOW');
    const infra = itemsOf(items, 'INFRASTRUCTURE', 'DEPLOYMENT', 'OBSERVABILITY');

    const inline = (items: KnowledgeItemSummary[]): string | null => {
      if (items.length === 0) return null;
      return items
        .map((i) => {
          const id = i.externalId ? `\`${i.externalId}\` ` : '';
          const desc = i.description?.trim();
          return desc
            ? `- **${id}${i.title}**: ${singleLine(desc)}`
            : `- **${id}${i.title}**`;
        })
        .join('\n');
    };

    return [
      '> Copy this section (or the entire document) into any AI coding agent —',
      '> Claude, ChatGPT, Cursor, Copilot, Gemini, etc. — and ask it to build the',
      '> application from scratch. Everything needed to implement is embedded below.',
      '',
      '## Role',
      '',
      `You are a senior full-stack engineering team tasked with building **${ctx.projectName}** as a complete, production-ready application. Start from an empty repository and implement everything described in this document. Do not ask for clarification on items already specified; make pragmatic, well-documented decisions for anything left open and list them in the handoff notes.`,
      '',
      '## Product Brief',
      '',
      `**Idea:** ${ctx.idea}`,
      '',
      scope.length > 0
        ? this.inlineSection('**Scope / MVP / Success metrics:**', inline(scope))
        : null,
      personas.length > 0 ? this.inlineSection('**Audience / personas:**', inline(personas)) : null,
      frs.length > 0 ? this.inlineSection('**Functional requirements (source of truth):**', inline(frs)) : null,
      nfr.length > 0 ? this.inlineSection('**Non-functional requirements & constraints:**', inline(nfr)) : null,
      '',
      '## Technology Stack',
      '',
      techs.length > 0 ? this.inlineSection('**Recommended technologies:**', inline(techs)) : '- Choose a mainstream, production-proven stack and state your choice.',
      llms.length > 0 ? this.inlineSection('**LLM / AI selections:**', inline(llms)) : null,
      ai.length > 0 ? this.inlineSection('**AI architecture notes:**', inline(ai)) : null,
      infra.length > 0 ? this.inlineSection('**Infrastructure / deployment / observability:**', inline(infra)) : null,
      '',
      '## Data Model',
      '',
      tables.length > 0 ? this.inlineSection('**Entities / tables:**', inline(tables)) : null,
      rels.length > 0 ? this.inlineSection('**Relationships:**', inline(rels)) : null,
      dbConstraints.length > 0 ? this.inlineSection('**Constraints:**', inline(dbConstraints)) : null,
      indexes.length > 0 ? this.inlineSection('**Indexes:**', inline(indexes)) : null,
      dictionary.length > 0 ? this.inlineSection('**Data dictionary:**', inline(dictionary)) : null,
      tables.length === 0
        ? '- Derive a clean relational schema from the functional requirements and document it in a migrations file.'
        : null,
      '',
      '## API Specification',
      '',
      apis.length > 0
        ? this.inlineSection('**Endpoints & contracts:**', inline(apis))
        : '- Design a REST (or equivalent) API covering every functional requirement, with request/response contracts, validation rules, error codes, auth, and pagination.',
      eventFlow.length > 0 ? this.inlineSection('**Events / async flows:**', inline(eventFlow)) : null,
      '',
      '## User Interface',
      '',
      screens.length > 0 ? this.inlineSection('**Screens to build:**', inline(screens)) : null,
      journeys.length > 0 ? this.inlineSection('**User journeys to support:**', inline(journeys)) : null,
      ux.length > 0 ? this.inlineSection('**UX / accessibility guidelines:**', inline(ux)) : null,
      '',
      '## Security',
      '',
      security.length > 0
        ? this.inlineSection('**Auth, encryption, compliance, threat model:**', inline(security))
        : '- Implement standard production security: hashed passwords, JWT/session auth, role-based access control, input validation, rate limiting, HTTPS, audit logging, and secret management.',
      '',
      '## Quality & Testing',
      '',
      qa.length > 0 ? this.inlineSection('**Test plan & cases:**', inline(qa)) : null,
      validation.length > 0 ? this.inlineSection('**Validation findings to resolve:**', inline(validation)) : null,
      qa.length === 0 && validation.length === 0
        ? '- Write unit tests for core logic, integration tests for APIs + DB, and end-to-end tests for the main user journeys; include the edge cases implied by the requirements.'
        : null,
      '',
      '## Build Instructions',
      '',
      [
        '1. Scaffold the repository (monorepo or two apps: backend API + frontend web app).',
        '2. Implement the data layer: migrations, seed data, repositories, indexes, and constraints.',
        '3. Implement the API: routes, validation, error handling, auth/authz, logging, rate limiting.',
        '4. Implement the frontend: layout, routing, state management, API client, forms, loading/error/empty states.',
        '5. Wire AI/LLM features using the LLM selections above with retries, timeouts, and structured outputs.',
        '6. Add tests (unit, integration, e2e) and a CI pipeline.',
        '7. Provide `.env.example`, `docker-compose.yml`, and deployment manifests.',
        '8. Write a README with setup, run, and deploy instructions.',
        '9. Run the full test suite and fix failures before finishing.',
      ].join('\n'),
      '',
      '## Definition of Done',
      '',
      [
        '- [ ] Every functional requirement has a working implementation path (UI + API + data).',
        '- [ ] Database schema matches the data model section (or a justified improvement).',
        '- [ ] Auth, authorization, and security controls from the Security section are implemented.',
        '- [ ] Error handling, validation, and edge cases are covered in code and tests.',
        '- [ ] Automated tests pass in CI.',
        '- [ ] Local setup works from a clean clone using documented env vars.',
        '- [ ] Handoff notes list any deliberate deviations or open decisions.',
      ].join('\n'),
    ]
      .filter((part): part is string => typeof part === 'string' && part.trim().length > 0)
      .join('\n\n');
  }

  private inlineSection(label: string, body: string | null): string | null {
    if (!body) return null;
    return `${label}\n\n${body}`;
  }
}

function itemsOf(items: KnowledgeItemSummary[], ...types: string[]): KnowledgeItemSummary[] {
  const set = new Set(types);
  return items.filter((i) => set.has(i.type));
}

function singleLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}
