import { Injectable } from '@nestjs/common';
import { LlmService } from '../llm/llm.service';
import type { AgentContext, AgentResult, KnowledgeItemSummary } from './types';

@Injectable()
export class CompilerService {
  constructor(private readonly llm: LlmService) {}

  async run(ctx: AgentContext): Promise<AgentResult> {
    // Build the detailed package from full RKB data (no truncation of stored facts).
    // LLM is only used for a short executive narrative on top.
    const body = this.compileFromKnowledge(ctx);
    let executiveSummary = '';

    try {
      const r = await this.llm.generateText([
        {
          role: 'system',
          content:
            'Write a detailed Executive Summary (250-400 words) for a software engineering documentation package. Cover problem, solution, users, MVP scope, key risks, and recommended next steps. Use professional prose. Do not invent features not implied by the idea.',
        },
        {
          role: 'user',
          content: `Project: ${ctx.projectName}\n\nIdea:\n${ctx.idea}\n\nKey signals:\n${this.briefSignals(ctx.knowledgeItems)}`,
        },
      ]);
      executiveSummary = r.content.trim();
    } catch {
      executiveSummary = this.fallbackExecutiveSummary(ctx);
    }

    const documentContent = [
      `# ${ctx.projectName}`,
      '',
      `> Generated by AI Software Engineering Platform — Compiler Agent`,
      '',
      `## 1. Executive Summary`,
      '',
      executiveSummary,
      '',
      body,
    ].join('\n');

    return {
      success: true,
      agentKey: 'compiler',
      knowledgeItems: [{
        type: 'COMPILED_DOCUMENT',
        title: `${ctx.projectName} — Compiled Requirement Document`,
        description: `Executive Summary:

${executiveSummary}

Full document contains specifications, requirements, and technical details.`,
        status: 'CONFIRMED' as const,
        sourceCategory: 'ai_analysis' as const,
        confidence: 85,
      }],
      questions: [],
      documentContent,
      warnings: [],
    };
  }

  private briefSignals(items: KnowledgeItemSummary[]): string {
    const pick = (types: string[], n = 5) =>
      items
        .filter((i) => types.includes(i.type))
        .slice(0, n)
        .map((i) => `- [${i.type}] ${i.title}`)
        .join('\n');

    return [
      pick(['DISCOVERY_SUMMARY', 'BA_SUMMARY', 'PRODUCT_VISION', 'MVP_SCOPE']),
      pick(['FEATURE', 'MODULE', 'FUNCTIONAL_REQUIREMENT'], 8),
      pick(['SECURITY_REPORT', 'ESTIMATION_REPORT', 'VALIDATION_SCORES'], 3),
    ]
      .filter(Boolean)
      .join('\n');
  }

  private fallbackExecutiveSummary(ctx: AgentContext): string {
    const discovery = itemsOf(ctx.knowledgeItems, 'DISCOVERY_SUMMARY')[0];
    return [
      `${ctx.projectName} addresses the following opportunity:`,
      '',
      ctx.idea,
      '',
      discovery?.description ??
        'The multi-agent pipeline produced discovery, requirements, architecture, security, QA, and estimation artifacts documented in the sections below.',
    ].join('\n');
  }

  private compileFromKnowledge(ctx: AgentContext): string {
    const items = ctx.knowledgeItems;
    const sections: string[] = [];

    sections.push(this.section('2. Discovery Report', [
      this.block('Problem & Solution', items, ['DISCOVERY_SUMMARY']),
      this.list('Confirmed Facts', items, ['CONFIRMED_FACT']),
      this.list('Business Goals', items, ['BUSINESS_GOAL']),
      this.list('User Goals', items, ['USER_GOAL']),
      this.list('User Types', items, ['USER_TYPE']),
      this.list('Early Risks', items, ['RISK']),
      this.list('Assumptions', items, ['ASSUMPTION']),
    ]));

    sections.push(this.section('3. Research Report', [
      this.block('Research Summary', items, ['RESEARCH_SUMMARY']),
      this.list('Competitors', items, ['COMPETITOR']),
      this.list('Technology Suggestions', items, ['TECHNOLOGY_SUGGESTION']),
      this.list('API / Integration Landscape', items, ['API_RESEARCH']),
      this.list('Compliance Notes', items, ['COMPLIANCE_NOTE']),
      this.list('Industry Standards', items, ['INDUSTRY_STANDARD']),
      this.list('Research Risks', items, ['RESEARCH_RISK']),
    ]));

    sections.push(this.section('4. Business Requirements (BRD)', [
      this.block('Business Analysis Summary', items, ['BA_SUMMARY']),
      this.list('Business Objectives', items, ['BUSINESS_OBJECTIVE']),
      this.list('Stakeholders', items, ['STAKEHOLDER']),
      this.detailedList('Business Requirements', items, ['BUSINESS_REQUIREMENT']),
      this.detailedList('Business Rules', items, ['BUSINESS_RULE']),
      this.list('Constraints', items, ['CONSTRAINT']),
      this.list('Business Risks', items, ['BUSINESS_RISK']),
      this.block('Scope', items, ['SCOPE']),
    ]));

    sections.push(this.section('5. Product Requirements (PRD)', [
      this.block('Product Vision', items, ['PRODUCT_VISION']),
      this.block('Value Proposition', items, ['VALUE_PROPOSITION']),
      this.list('Personas', items, ['PERSONA']),
      this.list('Modules', items, ['MODULE']),
      this.detailedList('Features (Prioritized)', items, ['FEATURE']),
      this.block('MVP Scope', items, ['MVP_SCOPE']),
      this.list('Success Metrics', items, ['SUCCESS_METRIC']),
    ]));

    sections.push(this.section('6. Software Requirements Specification (SRS)', [
      this.intro(
        'Functional requirements below include actors, modules, priorities, acceptance criteria, validation rules, and error conditions where captured by the Requirements Agent.',
      ),
      this.detailedList('Functional Requirements', items, ['FUNCTIONAL_REQUIREMENT']),
      this.list('Non-Functional / Constraints', items, ['CONSTRAINT']),
      this.list('Dependencies & Integrations', items, ['API_RESEARCH', 'API_SPEC', 'TECHNOLOGY_SUGGESTION']),
    ]));

    sections.push(this.section('7. User Stories & Use Cases', [
      this.detailedList('User Stories', items, ['USER_STORY']),
      this.scenarioGuidance(),
    ]));

    sections.push(this.section('8. UX Specification', [
      this.block('UX Summary & Navigation', items, ['UX_SUMMARY']),
      this.list('UX Personas', items, ['UX_PERSONA', 'PERSONA']),
      this.detailedList('User Journeys', items, ['USER_JOURNEY']),
      this.detailedList('Screen Inventory', items, ['SCREEN']),
      this.list('UX Guidelines', items, ['UX_GUIDELINE']),
      this.list('Accessibility Requirements', items, ['ACCESSIBILITY_REQUIREMENT']),
      this.detailedList('Wireframe Descriptions', items, ['WIREFRAME']),
    ]));

    sections.push(this.section('9. Database Design', [
      this.block('Design Summary / ER Overview', items, ['DATABASE_DESIGN']),
      this.detailedList('Tables', items, ['DB_TABLE']),
      this.detailedList('Relationships', items, ['DB_RELATIONSHIP']),
      this.list('Constraints', items, ['DB_CONSTRAINT']),
      this.list('Indexes', items, ['DB_INDEX']),
      this.detailedList('Data Dictionary', items, ['DATA_DICTIONARY']),
    ]));

    sections.push(this.section('10. AI Architecture', [
      this.block('AI Architecture Summary', items, ['AI_ARCHITECTURE']),
      this.list('LLM Selection', items, ['LLM_SELECTION']),
      this.detailedList('Prompt Strategy', items, ['PROMPT_STRATEGY']),
      this.list('Embeddings', items, ['EMBEDDING_DESIGN']),
      this.list('Vector Store', items, ['VECTOR_STORE']),
      this.list('Memory / Context', items, ['AI_MEMORY']),
      this.detailedList('Guardrails', items, ['AI_GUARDRAIL']),
    ]));

    sections.push(this.section('11. Solution Architecture & API Specification', [
      this.block('Architecture Summary', items, ['SOLUTION_ARCHITECTURE']),
      this.detailedList('System Components', items, ['SYSTEM_COMPONENT']),
      this.detailedList('API Specifications', items, ['API_SPEC']),
      this.list('Events / Queues', items, ['EVENT_FLOW']),
      this.list('Infrastructure', items, ['INFRASTRUCTURE']),
      this.list('Deployment', items, ['DEPLOYMENT']),
      this.list('Logging & Monitoring', items, ['OBSERVABILITY']),
    ]));

    sections.push(this.section('12. Security Report & Threat Model', [
      this.block('Security Summary', items, ['SECURITY_REPORT']),
      this.detailedList('Authentication & Authorization', items, ['SECURITY_AUTH']),
      this.detailedList('OWASP Findings', items, ['OWASP_FINDING']),
      this.list('Encryption & Secrets', items, ['SECURITY_ENCRYPTION']),
      this.list('API Security', items, ['API_SECURITY']),
      this.list('Compliance', items, ['SECURITY_COMPLIANCE', 'COMPLIANCE_NOTE']),
      this.detailedList('Threat Model', items, ['THREAT_MODEL']),
    ]));

    sections.push(this.section('13. QA Strategy & Test Cases', [
      this.block('QA Plan & Strategy', items, ['QA_PLAN']),
      this.list('Test Plan Items', items, ['TEST_PLAN_ITEM']),
      this.detailedList('Functional Test Cases', items, ['TEST_CASE']),
      this.detailedList('Regression Tests', items, ['REGRESSION_TEST']),
      this.detailedList('Performance Tests', items, ['PERFORMANCE_TEST']),
      this.detailedList('Security Tests', items, ['SECURITY_TEST']),
      this.testScenarioGuidance(),
    ]));

    sections.push(this.section('14. Estimation & Sprint Plan', [
      this.block('Estimation Summary', items, ['ESTIMATION_REPORT']),
      this.list('Team Composition', items, ['TEAM_ROLE']),
      this.detailedList('Timeline', items, ['TIMELINE']),
      this.list('Cost Estimate', items, ['COST_ESTIMATE']),
      this.detailedList('Sprint Plan', items, ['SPRINT_PLAN']),
      this.list('Estimation Risks', items, ['ESTIMATION_RISK']),
    ]));

    sections.push(this.section('15. Risks & Gap Analysis', [
      this.list('Product / Discovery Risks', items, ['RISK', 'BUSINESS_RISK', 'RESEARCH_RISK']),
      this.list('Security Risks', items, ['OWASP_FINDING', 'THREAT_MODEL']),
      this.list('Estimation Risks', items, ['ESTIMATION_RISK']),
      this.block('Validation Findings', items, ['VALIDATION_SCORES']),
      this.gapGuidance(),
    ]));

    sections.push(this.section('16. Validation Summary', [
      this.block('Critic / Validation Scores', items, ['VALIDATION_SCORES']),
      this.outro(),
    ]));

    sections.push(this.section('17. Appendix — Full Knowledge Inventory', [
      this.inventory(items),
    ]));

    return sections.filter(Boolean).join('\n\n');
  }

  private section(title: string, parts: Array<string | null>): string {
    const body = parts.filter((p): p is string => !!p && p.trim().length > 0).join('\n\n');
    if (!body.trim()) {
      return `## ${title}\n\n_No artifacts were generated for this section._`;
    }
    return `## ${title}\n\n${body}`;
  }

  private intro(text: string): string {
    return text;
  }

  private block(label: string, items: KnowledgeItemSummary[], types: string[]): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i) => {
        const header = i.externalId ? `**${i.externalId} — ${i.title}**` : `**${i.title}**`;
        return `${header}\n\n${i.description?.trim() || '_No description provided._'}`;
      }),
    ].join('\n');
  }

  private list(label: string, items: KnowledgeItemSummary[], types: string[]): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i) => {
        const id = i.externalId ? `\`${i.externalId}\` ` : '';
        const desc = i.description?.trim();
        return desc
          ? `- **${id}${i.title}**: ${singleLine(desc)}`
          : `- **${id}${i.title}**`;
      }),
    ].join('\n');
  }

  private detailedList(label: string, items: KnowledgeItemSummary[], types: string[]): string | null {
    const matched = itemsOf(items, ...types);
    if (matched.length === 0) return null;
    return [
      `### ${label}`,
      '',
      ...matched.map((i, idx) => {
        const id = i.externalId ? `${i.externalId} — ` : '';
        return [
          `#### ${idx + 1}. ${id}${i.title}`,
          '',
          i.description?.trim() || '_No detailed description captured._',
          '',
          i.status ? `_Status: ${i.status}_` : '',
        ]
          .filter(Boolean)
          .join('\n');
      }),
    ].join('\n');
  }

  private scenarioGuidance(): string {
    return [
      '### Scenario Coverage Checklist',
      '',
      'For each user story / FR above, implementation and QA should explicitly cover:',
      '',
      '1. **Happy path** — primary successful flow with valid inputs',
      '2. **Validation failures** — missing/invalid fields, malformed files, bad formats',
      '3. **Authorization failures** — unauthenticated / unauthorized access',
      '4. **Empty / edge states** — no data, first-time user, large payloads',
      '5. **Concurrency / retries** — duplicate submissions, network retries, idempotency',
      '6. **External dependency failures** — OCR/LLM/API timeouts and degraded mode',
      '7. **Auditability** — who did what, when, with which artifact',
    ].join('\n');
  }

  private testScenarioGuidance(): string {
    return [
      '### Recommended End-to-End Scenarios',
      '',
      '- New user registration → login → upload brochure → view extraction → receive recommendations',
      '- Invalid brochure upload (wrong type/corrupt/oversized) → clear error + retry',
      '- Partial extraction confidence → human review / confirmation step',
      '- Area research with missing geo data → graceful fallback messaging',
      '- Admin views audit logs and security events',
      '- Performance: concurrent uploads and recommendation generation under load',
      '- Security: auth bypass attempts, IDOR on brochure/project IDs, injection on metadata fields',
    ].join('\n');
  }

  private gapGuidance(): string {
    return [
      '### How to Use Gap Analysis',
      '',
      '- Treat Critic CRITICAL/HIGH issues as release blockers until resolved or explicitly accepted',
      '- Trace each FR to at least one test case and one UI screen',
      '- Confirm every MVP feature has data model + API + UX coverage',
      '- Re-run Validation after major requirement changes',
    ].join('\n');
  }

  private outro(): string {
    return [
      '### Sign-off Notes',
      '',
      'This package consolidates outputs from Discovery, Research, Business Analysis, Product Management, Requirements, UX, Data/AI/Solution Architecture, Security, QA, Estimation, and Critic agents.',
      '',
      'Recommended next step: resolve open validation issues, confirm MVP scope with stakeholders, then begin Sprint 1 implementation against the prioritized FRs and sprint plan.',
    ].join('\n');
  }

  private inventory(items: KnowledgeItemSummary[]): string {
    const counts = new Map<string, number>();
    for (const i of items) {
      counts.set(i.type, (counts.get(i.type) ?? 0) + 1);
    }
    const rows = [...counts.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([type, count]) => `| ${type} | ${count} |`)
      .join('\n');

    return [
      `Total knowledge items: **${items.length}**`,
      '',
      '| Type | Count |',
      '|---|---:|',
      rows,
    ].join('\n');
  }
}

function itemsOf(items: KnowledgeItemSummary[], ...types: string[]): KnowledgeItemSummary[] {
  const set = new Set(types);
  return items.filter((i) => set.has(i.type));
}

function singleLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}
