import { Injectable, Logger } from '@nestjs/common';
import { z } from 'zod';
import { LlmService } from '../llm/llm.service';
import { RkbService } from '../rkb/rkb.service';
import type { AgentContext, AgentResult } from './types';
import { safeJsonParse } from './agent.utils';

const ContradictionSchema = z.object({
  contradictions: z.array(z.object({
    itemA: z.string(),
    itemB: z.string(),
    category: z.string(),
    description: z.string(),
    impact: z.string(),
    resolution: z.string().nullish(),
    requiresHumanDecision: z.boolean(),
  })).nullish().default([]),
  assumptions: z.array(z.object({
    externalId: z.string(),
    title: z.string(),
    description: z.string(),
    riskLevel: z.enum(['LOW', 'MEDIUM', 'HIGH']),
    impact: z.string(),
    validationNeeded: z.string().nullish(),
  })).nullish().default([]),
  debateSummary: z.string().nullish(),
  reasoningTraces: z.array(z.string()).nullish().default([]),
  agentPositions: z.array(z.object({
    agentKey: z.string(),
    position: z.string(),
    reasoning: z.string(),
    alternatives: z.array(z.string()).optional(),
  })).nullish().default([]),
});

const SYSTEM = `You are a Debate & Validation Agent for a software Requirements Engineering system.

Your role is to:
1. Review ALL knowledge items generated by previous agents
2. Detect CONTRADICTIONS between requirements
3. Identify and flag ASSUMPTIONS that need validation
4. Simulate a multi-agent debate showing different perspectives
5. Provide a debate summary explaining trade-offs

For contradictions, identify pairs of items that conflict.
For assumptions, flag items marked as ASSUMED that need validation.
For the debate, simulate positions from different agent perspectives (e.g., architect vs. security vs. product manager).

Each contradiction should include which items conflict, the impact, and a recommended resolution.
Each assumption should include risk level and what validation is needed.`;

@Injectable()
export class DebateService {
  private readonly logger = new Logger(DebateService.name);

  constructor(
    private readonly llm: LlmService,
    private readonly rkb: RkbService,
  ) {}

  async run(ctx: AgentContext): Promise<AgentResult> {
    const knowledgeContext = await this.rkb.getKnowledgeContext(ctx.projectId);
    const allItems = knowledgeContext.map(k =>
      `[${k.externalId ?? '?'}] ${k.type}: ${k.title}\n  ${k.description ?? ''}\n  Status: ${k.status}  Source: ${k.sourceCategory ?? 'N/A'}`
    ).join('\n\n');

    const userMsg = `Project: ${ctx.projectName}\n\nAll Knowledge Items:\n${allItems}\n\nOriginal Idea:\n${ctx.idea}`;

    const r = await this.llm.generateStructured([
      { role: 'system', content: SYSTEM },
      { role: 'user', content: userMsg },
    ]);

    const data = ContradictionSchema.parse(safeJsonParse(r.content));

    // Save contradictions as validation issues
    const validationIssues: Array<{
      severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
      category: string;
      problem: string;
      impact?: string;
      evidence?: string;
      recommendedCorrection?: string;
      requiresHumanDecision?: boolean;
      affectedIds?: string[];
      sourceAgent?: string;
    }> = data.contradictions.map((c) => ({
      severity: c.requiresHumanDecision ? 'CRITICAL' as const : 'HIGH' as const,
      category: 'CONTRADICTION',
      problem: c.description,
      impact: c.impact,
      evidence: `Item A: ${c.itemA}\nItem B: ${c.itemB}`,
      recommendedCorrection: c.resolution ?? 'Requires human review',
      requiresHumanDecision: c.requiresHumanDecision,
      affectedIds: [c.itemA, c.itemB],
      sourceAgent: 'debate',
    }));

    // Save high-risk assumptions as validation issues too
    for (const a of data.assumptions) {
      if (a.riskLevel === 'HIGH' || a.riskLevel === 'MEDIUM') {
        validationIssues.push({
          severity: (a.riskLevel === 'HIGH' ? 'HIGH' : 'MEDIUM') as "CRITICAL" | "HIGH" | "MEDIUM",
          category: 'ASSUMPTION',
          problem: `Unvalidated assumption: ${a.title}`,
          impact: a.impact,
          evidence: a.description,
          recommendedCorrection: a.validationNeeded ?? 'Validate with stakeholder',
          requiresHumanDecision: true,
          sourceAgent: 'debate',
        });
      }
    }

    // Knowledge items from the debate itself
    const knowledgeItems = [
      {
        type: 'DEBATE_SUMMARY',
        title: 'Multi-Agent Debate Summary',
        description: data.debateSummary,
        status: 'CONFIRMED' as const,
        sourceCategory: 'debate' as const,
        reasoning: data.reasoningTraces.join('\n'),
      },
      ...data.agentPositions.map((p) => ({
        type: 'AGENT_POSITION' as const,
        title: `${p.agentKey} Position`,
        description: `${p.position}\n\nReasoning: ${p.reasoning}${p.alternatives ? `\n\nAlternatives considered: ${p.alternatives.join(', ')}` : ''}`,
        status: 'CONFIRMED' as const,
        sourceCategory: 'debate' as const,
        reasoning: p.reasoning,
      })),
      ...data.assumptions.filter(a => a.riskLevel === 'HIGH').map((a) => ({
        type: 'RISKY_ASSUMPTION' as const,
        title: a.title,
        description: `${a.description}\n\nImpact: ${a.impact}\nValidation needed: ${a.validationNeeded ?? 'N/A'}`,
        status: 'DRAFT' as const,
        sourceCategory: 'ai_analysis' as const,
      })),
    ];

    return {
      success: true,
      agentKey: 'debate',
      knowledgeItems,
      validationIssues,
      questions: [],
      warnings: [],
      reasoningTraces: data.reasoningTraces,
      _tokens: { inputTokens: r.inputTokens, outputTokens: r.outputTokens, model: r.model },
    };
  }
}
