/**
 * Standardized skill definitions for the 15 structured agents.
 *
 * Document-generation skills (FRD / User Stories / Tech Arch / DB / API / SOW /
 * Build Prompt) are out of scope for Phase 5 — they remain in the legacy agent
 * module and are migrated in a later phase.
 *
 * Every definition declares:
 *   - key, version, status
 *   - model tier (Phase 2 routing)
 *   - prompt template key (PromptBuilder registry)
 *   - maxTokens / tokenBudget (output vs context ceiling)
 *   - input/output JSON Schema (forced structured output)
 *   - producedArtifacts (canonical kinds)
 *   - requiredContext (canonical domains)
 *   - validationRules + qualityGates
 *   - dependencies (skill ordering hints)
 */
import type { SkillDefinition } from './skill.types';
import { AGENT_STRUCTURED_SCHEMAS } from '../../llm/agent-json-schemas';

const schemaRefs = (n: string) => ({ $ref: `agent:${n}#/$defs/output` });

const string = { type: 'string' } as const;

export const SKILL_DEFINITIONS: ReadonlyArray<SkillDefinition> = [
  {
    key: 'discovery',
    name: 'Discovery',
    description: 'Analyzes the project idea, extracts domain context, and produces a P0-4 checkpoint.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:discovery',
    maxTokens: 3000,
    tokenBudget: 4000,
    inputSchema: { type: 'object', properties: { projectId: string, idea: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['discovery']?.schema ?? schemaRefs('discovery'),
    producedArtifacts: ['project_goal', 'assumption', 'actor', 'question', 'risk'],
    requiredContext: ['business_goals', 'assumptions'],
    validationRules: [
      { code: 'minQuestions', message: 'At least one blocking question when idea is sparse.' },
      { code: 'fingerprint-confidence', message: 'Each fact must carry a confidence score.' },
    ],
    qualityGates: ['knowledge-coverage'],
    dependencies: [],
    tool: { name: 'submit_discovery_output', schema: AGENT_STRUCTURED_SCHEMAS['discovery']?.schema ?? schemaRefs('discovery') },
  },
  {
    key: 'research',
    name: 'Research',
    description: 'Domain research, competitor scan, feasibility and standards.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'fast',
    promptKey: 'agent:research',
    maxTokens: 3000,
    tokenBudget: 6000,
    inputSchema: { type: 'object', properties: { projectId: string, topic: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['research']?.schema ?? schemaRefs('research'),
    producedArtifacts: ['domain', 'constraint'],
    requiredContext: ['business_goals', 'domain_knowledge'],
    validationRules: [{ code: 'sources-present', message: 'Every claim must reference a source.' }],
    qualityGates: ['knowledge-coverage'],
    dependencies: [{ skillKey: 'discovery', relation: 'REFINES', required: true }],
    tool: { name: 'submit_research_output', schema: AGENT_STRUCTURED_SCHEMAS['research']?.schema ?? schemaRefs('research') },
  },
  {
    key: 'business-analysis',
    name: 'Business Analysis',
    description: 'Goals, stakeholders, business rules and risk catalog.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:business-analysis',
    maxTokens: 3000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['business-analysis']?.schema ?? schemaRefs('business-analysis'),
    producedArtifacts: ['business_rule', 'actor', 'risk', 'assumption'],
    requiredContext: ['business_goals', 'actors', 'business_rules', 'risks'],
    validationRules: [{ code: 'br-id-format', message: 'Business rule IDs follow BR-* convention.' }],
    qualityGates: ['id-integrity'],
    dependencies: [{ skillKey: 'discovery', required: true }, { skillKey: 'research', required: true }],
    tool: { name: 'submit_business_analysis_output', schema: AGENT_STRUCTURED_SCHEMAS['business-analysis']?.schema ?? schemaRefs('business-analysis') },
  },
  {
    key: 'product-analysis',
    name: 'Product Analysis',
    description: 'Personas, features and epics for the product.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:product-analysis',
    maxTokens: 3000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['product-analysis']?.schema ?? schemaRefs('product-analysis'),
    producedArtifacts: ['actor', 'assumption', 'risk'],
    requiredContext: ['actors', 'business_rules', 'features', 'epics'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [{ skillKey: 'business-analysis', required: true }],
    tool: { name: 'submit_product_analysis_output', schema: AGENT_STRUCTURED_SCHEMAS['product-analysis']?.schema ?? schemaRefs('product-analysis') },
  },
  {
    key: 'requirements-engineering',
    name: 'Requirements Engineering',
    description: 'Produces functional + non-functional requirements and user stories.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'high',
    promptKey: 'agent:requirements-engineering',
    maxTokens: 6000,
    tokenBudget: 12000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['requirements-engineering']?.schema ?? schemaRefs('requirements-engineering'),
    producedArtifacts: ['requirement', 'non_functional_requirement', 'user_story'],
    requiredContext: [
      'business_goals',
      'business_rules',
      'actors',
      'features',
      'processes',
      'functional_requirements',
    ],
    validationRules: [
      { code: 'fr-id-format', message: 'Requirement IDs follow FR-* convention.' },
      { code: 'related-actors', message: 'Functional requirements must reference actors.' },
    ],
    qualityGates: ['id-integrity', 'knowledge-coverage'],
    dependencies: [
      { skillKey: 'product-analysis', required: true },
      { skillKey: 'business-analysis', required: true },
    ],
    tool: { name: 'submit_requirements_engineering_output', schema: AGENT_STRUCTURED_SCHEMAS['requirements-engineering']?.schema ?? schemaRefs('requirements-engineering') },
  },
  {
    key: 'ux-design',
    name: 'UX Design',
    description: 'Screens, journeys, accessibility and wireframes.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:ux-design',
    maxTokens: 3000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['ux-design']?.schema ?? schemaRefs('ux-design'),
    producedArtifacts: ['screen'],
    requiredContext: ['ui_screens', 'user_stories', 'acceptance_criteria', 'functional_requirements'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'requirements-engineering', required: true },
      { skillKey: 'product-analysis', required: true },
    ],
    tool: { name: 'submit_ux_output', schema: AGENT_STRUCTURED_SCHEMAS['ux-design']?.schema ?? schemaRefs('ux-design') },
  },
  {
    key: 'data-architecture',
    name: 'Data Architecture',
    description: 'Entities, relationships and persistence schema.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:data-architecture',
    maxTokens: 3000,
    tokenBudget: 10000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['data-architecture']?.schema ?? schemaRefs('data-architecture'),
    producedArtifacts: ['entity', 'relationship'],
    requiredContext: ['database_tables', 'functional_requirements'],
    validationRules: [{ code: 'entity-id-format', message: 'Entity IDs follow TBL-* convention.' }],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'ux-design', required: true },
      { skillKey: 'requirements-engineering', required: true },
    ],
    tool: { name: 'submit_data_architecture_output', schema: AGENT_STRUCTURED_SCHEMAS['data-architecture']?.schema ?? schemaRefs('data-architecture') },
  },
  {
    key: 'ai-architecture',
    name: 'AI Architecture',
    description: 'LLM prompts, embeddings, vector indexes, memory and guardrails.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:ai-architecture',
    maxTokens: 3000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['ai-architecture']?.schema ?? schemaRefs('ai-architecture'),
    producedArtifacts: ['architecture_decision'],
    requiredContext: ['non_functional_requirements', 'database_tables'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'data-architecture', required: true },
      { skillKey: 'ux-design', required: true },
    ],
    tool: { name: 'submit_ai_architecture_output', schema: AGENT_STRUCTURED_SCHEMAS['ai-architecture']?.schema ?? schemaRefs('ai-architecture') },
  },
  {
    key: 'solution-architecture',
    name: 'Solution Architecture',
    description: 'System architecture: components, events, deployment and observability.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'high',
    promptKey: 'agent:solution-architecture',
    maxTokens: 3000,
    tokenBudget: 12000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['solution-architecture']?.schema ?? schemaRefs('solution-architecture'),
    producedArtifacts: ['architecture_decision'],
    requiredContext: [
      'functional_requirements',
      'non_functional_requirements',
      'database_tables',
      'apis',
    ],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'ai-architecture', required: true },
      { skillKey: 'data-architecture', required: true },
    ],
    tool: { name: 'submit_solution_architecture_output', schema: AGENT_STRUCTURED_SCHEMAS['solution-architecture']?.schema ?? schemaRefs('solution-architecture') },
  },
  {
    key: 'security-review',
    name: 'Security Review',
    description: 'Threat modeling, OWASP coverage, security requirements and compliance.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:security-review',
    maxTokens: 3000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['security-review']?.schema ?? schemaRefs('security-review'),
    producedArtifacts: ['security_requirement', 'risk'],
    requiredContext: ['non_functional_requirements', 'risks', 'architecture_decision'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'solution-architecture', required: true },
      { skillKey: 'ai-architecture', required: true },
    ],
    tool: { name: 'submit_security_output', schema: AGENT_STRUCTURED_SCHEMAS['security-review']?.schema ?? schemaRefs('security-review') },
  },
  {
    key: 'qa-planning',
    name: 'QA Planning',
    description: 'Test strategy, test cases and performance/load plans.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:qa-planning',
    maxTokens: 6000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['qa-planning']?.schema ?? schemaRefs('qa-planning'),
    producedArtifacts: ['test_case'],
    requiredContext: ['test_cases', 'functional_requirements', 'acceptance_criteria'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [
      { skillKey: 'security-review', required: true },
      { skillKey: 'solution-architecture', required: true },
    ],
    tool: { name: 'submit_qa_output', schema: AGENT_STRUCTURED_SCHEMAS['qa-planning']?.schema ?? schemaRefs('qa-planning') },
  },
  {
    key: 'estimation',
    name: 'Estimation',
    description: 'Effort, cost and team estimates per scope item.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'fast',
    promptKey: 'agent:estimation',
    maxTokens: 3000,
    tokenBudget: 6000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['estimation']?.schema ?? schemaRefs('estimation'),
    producedArtifacts: ['estimate', 'scope_item'],
    requiredContext: ['functional_requirements', 'user_stories', 'features'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [{ skillKey: 'qa-planning', required: true }, { skillKey: 'security-review', required: true }],
    tool: { name: 'submit_estimation_output', schema: AGENT_STRUCTURED_SCHEMAS['estimation']?.schema ?? schemaRefs('estimation') },
  },
  {
    key: 'validation',
    name: 'Critic / Validation',
    description: 'Reviews requirements for quality, consistency and ID integrity.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'high',
    promptKey: 'agent:validation',
    maxTokens: 4000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['validation']?.schema ?? schemaRefs('validation'),
    producedArtifacts: [], // validator-only — produces issues, not canonical items
    requiredContext: [
      'functional_requirements',
      'business_rules',
      'risks',
      'architecture_decision',
    ],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [{ skillKey: 'estimation', required: true }],
    tool: { name: 'submit_validation_output', schema: AGENT_STRUCTURED_SCHEMAS['validation']?.schema ?? schemaRefs('validation') },
  },
  {
    key: 'debate',
    name: 'Debate',
    description: 'Multi-agent debate on validation findings; produces decisions + revisions.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'high',
    promptKey: 'agent:debate',
    maxTokens: 5000,
    tokenBudget: 8000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['debate']?.schema ?? schemaRefs('debate'),
    producedArtifacts: ['architecture_decision'],
    requiredContext: ['functional_requirements', 'business_rules'],
    validationRules: [],
    qualityGates: ['id-integrity'],
    dependencies: [{ skillKey: 'validation', required: true }],
    tool: { name: 'submit_debate_output', schema: AGENT_STRUCTURED_SCHEMAS['debate']?.schema ?? schemaRefs('debate') },
  },
  {
    key: 'gap-analysis',
    name: 'Gap Analysis',
    description: 'Analyzes gaps across artifacts + documents, returns review-gated proposals.',
    version: '1.0',
    status: 'ACTIVE',
    modelTier: 'standard',
    promptKey: 'agent:gap-analysis',
    maxTokens: 3000,
    tokenBudget: 12000,
    inputSchema: { type: 'object', properties: { projectId: string } },
    outputSchema: AGENT_STRUCTURED_SCHEMAS['gap-analysis']?.schema ?? schemaRefs('gap-analysis'),
    producedArtifacts: [], // gap analysis produces findings/proposals, not canonical items
    requiredContext: [
      'functional_requirements',
      'acceptance_criteria',
      'test_cases',
      'user_stories',
      'scope_item',
      'document_summaries',
    ],
    validationRules: [],
    qualityGates: ['id-integrity', 'knowledge-coverage'],
    dependencies: [{ skillKey: 'debate', required: true }],
    tool: { name: 'submit_gap_analysis_output', schema: AGENT_STRUCTURED_SCHEMAS['gap-analysis']?.schema ?? schemaRefs('gap-analysis') },
  },
];

export function getSkillDefinition(key: string): SkillDefinition | undefined {
  return SKILL_DEFINITIONS.find((s) => s.key === key);
}

export function listSkillDefinitions(): readonly SkillDefinition[] {
  return SKILL_DEFINITIONS;
}
